### ISSUE TITLE
Unable to find ADT7410 temp sensor

### ISSUE THREAD

**Issue by doraess** [adafruit/Adafruit_CircuitPython_ADT7410#4]
Hi,

I get the following error in de basic example:

"ValueError: Unable to find ADT7410 at i2c address 0x48"

**Comment by jerryneedell** [comment]
This is most likely a wiring issue. Please post the code you are executing and describe the hardware configuration (what boards, what version of Circuitpython).

**Comment by doraess** [comment]
Brand new PyPortal, and just the basic example.

**Comment by jerryneedell** [comment]
odd -- It works fine on mine. 
I suggest posting to the forum for support https://forums.adafruit.com/viewforum.php?f=60  
this is mainly a place to discuss issues with the code itself.

**Comment by jerryneedell** [comment]
It is not clear to me why it should matter for this test, but did you update the PyPortal following the guide?
https://learn.adafruit.com/adafruit-pyportal/updating-your-pyportal

**Comment by Niko-La** [comment]
I get the same issue. +1

**Comment by caternuson** [comment]
Please post in the forums with photos showing how everything is connected.
https://forums.adafruit.com/

**Comment by makermelissa** [comment]
As a data point, I just happened to test this earlier today successfully on a Raspberry Pi.

**Comment by caternuson** [comment]
Also, PyPortal specific, check this:
https://learn.adafruit.com/adafruit-pyportal/pyportal-hardware-faq#faq-3023716

**Comment by caternuson** [comment]
If anyone above posted in the forums, please post a link to the thread here. Closing this for now.
